
total_epochs: 40
imgs_per_gpu: &b 4
workers_per_gpu: 8
checkpoint_epoch_interval: 1

dataset:
    type: "nuscenes"
    frame_ids: &f [0, -1, 1]
    width: &w 384
    height: &h 192

    nuscenes:
      weather: "day"
      down_scale: False
      num_out_scales: 5
      gen_equ: True
      equ_limit: 0.004
      resize: True

model:
  name: "mono2"

  depth_num_layers: 50
  pose_num_layers: 18

  learning_rate: 1.0e-4

  frame_ids: *f
  imgs_per_gpu: *b
  height: *h
  width: *w
  scales: [0, 1, 2, 3, 4]
  min_depth: 0.1
  max_depth: 100.0

  use_equ: True

  automask: True
  disp_norm: True

  disparity_smoothness: 1.0e-3
